export const GROUPS = [
  {
    collapsed: false,
    color: 'red',
    id: 1698879258,
    title: 'Wikipedia',
    windowId: 273536770,
  },
  {
    collapsed: true,
    color: 'cyan',
    id: 931573972,
    title: 'Example',
    windowId: 273536770,
  },
]

export const TABS = [
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: 'https://github.githubassets.com/favicons/favicon.svg',
    groupId: -1,
    height: 1210,
    highlighted: false,
    id: 273536828,
    incognito: false,
    index: 0,
    lastAccessed: 1736533566718.591,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: 'complete',
    title:
      'GitHub · Build and ship software on a single, collaborative platform · GitHub',
    url: 'https://github.com/',
    width: 2161,
    windowId: 273536770,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl:
      'https://www.mozilla.org/media/img/favicons/mozilla/m24/favicon.d0be64e474b1.ico',
    groupId: -1,
    height: 1210,
    highlighted: false,
    id: 273536833,
    incognito: false,
    index: 1,
    lastAccessed: 1736533572023.703,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: 'complete',
    title: 'Mozilla - Internet for people, not profit (US)',
    url: 'https://www.mozilla.org/en-US/',
    width: 2161,
    cookieStoreId: 'firefox-container-3',
    windowId: 273536770,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl:
      'https://www.redditstatic.com/shreddit/assets/favicon/64x64.png',
    groupId: -1,
    height: 1210,
    highlighted: false,
    id: 273536834,
    incognito: false,
    index: 2,
    lastAccessed: 1736533577792.505,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: 'complete',
    title: 'Potted Cats - cats in pots',
    url: 'https://www.reddit.com/r/pottedcats/',
    width: 2161,
    windowId: 273536770,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl:
      'https://developer.mozilla.org/favicon-48x48.bc390275e955dacb2e65.png',
    groupId: -1,
    height: 1210,
    highlighted: false,
    id: 273536839,
    incognito: false,
    index: 3,
    lastAccessed: 1736533594938.445,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: 'complete',
    title: 'CSS scrollbars styling - CSS: Cascading Style Sheets | MDN',
    url: 'https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_scrollbars_styling',
    width: 2161,
    cookieStoreId: 'firefox-container-4',
    windowId: 273536770,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl:
      'https://www.youtube.com/s/desktop/b5305900/img/logos/favicon_32x32.png',
    groupId: -1,
    height: 1210,
    highlighted: false,
    id: 273536842,
    incognito: false,
    index: 4,
    lastAccessed: 1736533600569.377,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: 'complete',
    title: 'YouTube',
    url: 'https://www.youtube.com/',
    width: 2161,
    windowId: 273536770,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: 'https://en.wikipedia.org/static/favicon/wikipedia.ico',
    groupId: 1698879258,
    height: 1210,
    highlighted: false,
    id: 273536845,
    incognito: false,
    index: 5,
    lastAccessed: 1736533682208.715,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: 'complete',
    title: 'Internet - Wikipedia',
    url: 'https://en.wikipedia.org/wiki/Internet',
    width: 2161,
    windowId: 273536770,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: 'https://en.wikipedia.org/static/favicon/wikipedia.ico',
    groupId: 1698879258,
    height: 1210,
    highlighted: false,
    id: 273536848,
    incognito: false,
    index: 6,
    lastAccessed: 1736533682678.763,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: 'complete',
    title: 'Internet protocol suite - Wikipedia',
    url: 'https://en.wikipedia.org/wiki/Internet_protocol_suite',
    width: 2161,
    windowId: 273536770,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: 'https://en.wikipedia.org/static/favicon/wikipedia.ico',
    groupId: 1698879258,
    height: 1210,
    highlighted: false,
    id: 273536851,
    incognito: false,
    index: 7,
    lastAccessed: 1736533682953.393,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: 'complete',
    title: 'World Wide Web - Wikipedia',
    url: 'https://en.wikipedia.org/wiki/World_Wide_Web',
    width: 2161,
    windowId: 273536770,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl:
      'https://ssl.gstatic.com/docs/doclist/images/drive_2022q3_32dp.png',
    groupId: -1,
    height: 1210,
    highlighted: false,
    id: 273536860,
    incognito: false,
    index: 8,
    lastAccessed: 1736533651455.288,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: 'complete',
    title: 'Home - Google Drive',
    url: 'https://drive.google.com/drive/home?dmr=1&ec=wgc-drive-globalnav-goto',
    width: 2161,
    cookieStoreId: 'firefox-container-2',
    windowId: 273536770,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: 'https://www.google.com/favicon.ico',
    groupId: -1,
    height: 1210,
    highlighted: false,
    id: 273536857,
    incognito: false,
    index: 9,
    lastAccessed: 1736533645165.505,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: 'complete',
    title: 'wool - Google Search',
    url: 'https://www.google.com/search?q=wool&oq=wool&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIQCAEQLhjHARjJAxjRAxiABDINCAIQLhjHARjRAxiABDIHCAMQABiABDINCAQQABiSAxiABBiKBTINCAUQABiSAxiABBiKBTIHCAYQABiABDINCAcQLhjHARjRAxiABDIHCAgQABiPAjIHCAkQABiPAtIBCDExMTlqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8',
    width: 2161,
    cookieStoreId: 'firefox-container-2',
    windowId: 273536770,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl:
      'https://mastodon.social/packs/media/icons/favicon-32x32-249409a6d9f300112c51af514d863112.png',
    groupId: -1,
    height: 1210,
    highlighted: false,
    id: 273536864,
    incognito: false,
    index: 10,
    lastAccessed: 1736533656812.486,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: 'complete',
    title: 'Explore - Mastodon',
    url: 'https://mastodon.social/explore',
    width: 2161,
    windowId: 273536770,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    groupId: 931573972,
    height: 1210,
    highlighted: false,
    id: 273536873,
    incognito: false,
    index: 11,
    lastAccessed: 1736533715494.369,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: 'complete',
    title: 'Example Domain',
    url: 'https://example.com/',
    width: 2161,
    windowId: 273536770,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    groupId: 931573972,
    height: 1210,
    highlighted: false,
    id: 273536876,
    incognito: false,
    index: 12,
    lastAccessed: 1736533714542.865,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: 'complete',
    title: 'Example Domain',
    url: 'https://example.com/',
    width: 2161,
    windowId: 273536770,
  },
  {
    active: true,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: 'https://letterboxd.com/favicon.ico',
    groupId: -1,
    height: 1210,
    highlighted: true,
    id: 273536867,
    incognito: false,
    index: 13,
    lastAccessed: 1736533843972.27,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: true,
    status: 'complete',
    title: 'Letterboxd • Social film discovery.',
    url: 'https://letterboxd.com/',
    width: 2161,
    windowId: 273536770,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: 'https://letterboxd.com/favicon.ico',
    groupId: -1,
    height: 1210,
    highlighted: false,
    id: 273536870,
    incognito: false,
    index: 14,
    lastAccessed: 1736533676963.31,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: 'complete',
    title: 'Frequent questions • Letterboxd',
    url: 'https://letterboxd.com/about/faq/',
    width: 2161,
    cookieStoreId: 'firefox-container-1',
    windowId: 273536770,
  },
]

export const CONTAINERS = [
  {
    name: 'Personal',
    icon: 'fingerprint',
    iconUrl: 'resource://usercontext-content/fingerprint.svg',
    color: 'blue',
    colorCode: '#37adff',
    cookieStoreId: 'firefox-container-1',
  },
  {
    name: 'Work',
    icon: 'briefcase',
    iconUrl: 'resource://usercontext-content/briefcase.svg',
    color: 'orange',
    colorCode: '#ff9f00',
    cookieStoreId: 'firefox-container-2',
  },
  {
    name: 'Banking',
    icon: 'dollar',
    iconUrl: 'resource://usercontext-content/dollar.svg',
    color: 'green',
    colorCode: '#51cd00',
    cookieStoreId: 'firefox-container-3',
  },
  {
    name: 'Shopping',
    icon: 'cart',
    iconUrl: 'resource://usercontext-content/cart.svg',
    color: 'pink',
    colorCode: '#ff4bda',
    cookieStoreId: 'firefox-container-4',
  },
]
